apiVersion: v1
kind: ConfigMap
metadata:
  name: loan-management-config
  namespace: loan-management
data:
  DB_HOST: loan-management-mysql.chua64y0evu2.ap-south-1.rds.amazonaws.com
  DB_PORT: "3306"
  DB_SSL: "false"
  DB_ALLOW_PUBLIC_KEY_RETRIEVAL: "true"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_SSL: "false"
  KAFKA_BOOTSTRAP: REPLACE_WITH_MSK_BOOTSTRAP_SERVERS
  KAFKA_SECURITY_PROTOCOL: SASL_SSL
  KAFKA_SASL_MECHANISM: PLAIN
  KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: https
  DOCUMENT_STORAGE_TYPE: s3
  DOCUMENT_S3_REGION: ap-south-1
  DOCUMENT_S3_KEY_PREFIX: documents/
  DOCUMENT_S3_PATH_STYLE_ACCESS: "false"
