apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loan-management-secrets
  namespace: loan-management
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: loan-management-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: loan-management-app-secrets-v2
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: loan-management-app-secrets-v2
        property: DB_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: loan-management-app-secrets-v2
        property: JWT_SECRET
