apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - document-service-serviceaccount.yaml
  - cluster-secret-store.yaml
  - external-secret.yaml
  - ingress.yaml
  - aws-s3-network-policy.yaml

patches:
  - path: configmap-patch.yaml
  - path: document-service-patch.yaml
  - path: security-context-patch.yaml

  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: ghcr-secret
