apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../namespace.yaml
  - ../configmap.yaml
  - ../network-policies.yaml
  - ../services.yaml
  - ../redis.yaml
  - ../kafka.yaml
  - ../loan-services.yaml
  - ../support-services.yaml
  - document-service-serviceaccount.yaml
  - app-secret-provider.yaml
  - secret-sync.yaml
  - secrets-serviceaccount.yaml
  - ingress.yaml
  - ../aws-s3-network-policy.yaml

patches:
  - path: configmap-patch.yaml
  - path: document-service-patch.yaml
