apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: loan-management
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: discovery-server
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: loan-management
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: api-gateway
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: loan-management
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: auth-service
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: loan-management
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: customer-service
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-service
  namespace: loan-management
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: loan-service
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repayment-service
  namespace: loan-management
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: repayment-service
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service
  namespace: loan-management
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: document-service
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: loan-management
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: notification-service
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
  namespace: loan-management
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: audit-service
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-service
  namespace: loan-management
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: dashboard-service
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
