#!/bin/bash
set -e

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS customer_db;
CREATE DATABASE IF NOT EXISTS loan_db;
CREATE DATABASE IF NOT EXISTS repayment_db;
CREATE DATABASE IF NOT EXISTS document_db;
CREATE DATABASE IF NOT EXISTS notification_db;
CREATE DATABASE IF NOT EXISTS audit_db;
CREATE DATABASE IF NOT EXISTS dashboard_db;

CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
ALTER USER '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON auth_db.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON customer_db.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON loan_db.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON repayment_db.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON document_db.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON notification_db.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON audit_db.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON dashboard_db.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;
EOSQL
