apiVersion: v1
kind: ConfigMap
metadata:
  name: loan-management-config
  namespace: loan-management
data:
  EUREKA_URL: http://discovery-server:8761/eureka/
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_SSL: "false"
  DB_ALLOW_PUBLIC_KEY_RETRIEVAL: "true"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_SSL: "false"
  KAFKA_BOOTSTRAP: kafka:29092
  KAFKA_SECURITY_PROTOCOL: PLAINTEXT
  KAFKA_SASL_MECHANISM: PLAIN
  KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: https
  DOCUMENT_STORAGE_TYPE: local
  DOCUMENT_S3_REGION: ap-south-1
  DOCUMENT_S3_KEY_PREFIX: documents/
  DOCUMENT_S3_PATH_STYLE_ACCESS: "false"
